# Basic
title: qinZhang
subtitle: 人间有味是清欢
welcome_message: 兴趣是最好的老师，但也需深知业精于勤，fighting！
description: 嗨，我是张钦，目前在上海一家知名金融科技公司从事后端(Java)开发！
creator: <a href="">@qinZhang</a>

url: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: ''}
    - {title: 订阅, description: 邮件订阅本站, url: ''}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: qinzhang
    # duoshuo:
# Social
social:
    weibo: https://weibo.com/2776266055/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    github: QinZhang1990/QinZhang1990.github.io
    mail: qzhang_ecnu@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
