# Basic
title: Joseph Zhang
subtitle: 不喧哗，自有声
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 嗨，我是张钦，刚毕业于华东师范大学地理信息系统专业，目前在上海一家Fintech公司，从事Java开发，作为一只编程小白，还有很长路的要走！
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    微博: https://weibo.com/2776266055/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    github: ''
    twitter: ''
    邮箱: qzhang_ecnu@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
