# Basic
title: Joseph Zhang
subtitle: 有思想，有行动，有未来
welcome_message: 也许，我们都曾来自于星星，生而孤独，静静散发着光芒，心在遥远的彼岸，期待着温柔的呼唤，爱的相拥 ——《星星上的人》
description: 嗨，我是张钦，刚刚毕业于华东师范大学地理信息系统专业，目前在上海一家Fintech公司从事数据处理与分析工作，作为一只职场小白，需要更多的埋头修行，请多多鼓励[抱拳]！
creator: <a href="">@Joseph Zhang</a>

url: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: ''}
    - {title: 关于, description: 了解更多关于我, url: ''}
    - {title: 订阅, description: 邮件订阅本站, url: ''}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: joseph-zhang
    # duoshuo:
# Social
social:
    weibo: https://weibo.com/2776266055/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    github: ''
    gplus: ''
    mail: qzhang_ecnu@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
