# Basic
title: Joseph Zhang
subtitle: 不喧哗，自有声
welcome_message: 欢迎来到我的个人博客，请多多指正！
description: 嗨，我是张钦，刚刚毕业于华东师范大学地理信息系统专业，目前在上海一家Fintech公司从事后台Java开发，作为一只编程小白，需要更多的埋头修行，请多多鼓励[抱拳]！
creator: <a href="">@Joseph Zhang</a>

url: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: ''}
    - {title: 关于, description: 了解更多关于我, url: ''}
    - {title: 订阅, description: 邮件订阅本站, url: ''}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: joseph_zhang
    # duoshuo:
# Social
social:
    weibo: https://weibo.com/2776266055/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    github: ''
    gplus: ''
    mail: qzhang_ecnu@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
